# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Projects/refSoM/refCC2/hw/vhfSystem.srcs/sources_1/bd/system/ip/system_system_ila_0_2/system_system_ila_0_2.xci
# IP: The module: 'system_system_ila_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/Projects/refSoM/refCC2/hw/adrv9361z7035_ccfmc_lvds.gen/sources_1/bd/system/ip/system_system_ila_0_2/bd_0/bd_1439.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1439 || ORIG_REF_NAME==bd_1439} -quiet] -quiet

# IP: e:/Projects/refSoM/refCC2/hw/adrv9361z7035_ccfmc_lvds.gen/sources_1/bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_0/bd_1439_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1439_ila_lib_0 || ORIG_REF_NAME==bd_1439_ila_lib_0} -quiet] -quiet

# XDC: e:/Projects/refSoM/refCC2/hw/adrv9361z7035_ccfmc_lvds.gen/sources_1/bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1439_ila_lib_0 || ORIG_REF_NAME==bd_1439_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/Projects/refSoM/refCC2/hw/adrv9361z7035_ccfmc_lvds.gen/sources_1/bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1439_ila_lib_0 || ORIG_REF_NAME==bd_1439_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/Projects/refSoM/refCC2/hw/adrv9361z7035_ccfmc_lvds.gen/sources_1/bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_0/bd_1439_ila_lib_0_ooc.xdc

# XDC: e:/Projects/refSoM/refCC2/hw/adrv9361z7035_ccfmc_lvds.gen/sources_1/bd/system/ip/system_system_ila_0_2/bd_0/bd_1439_ooc.xdc

# XDC: e:/Projects/refSoM/refCC2/hw/adrv9361z7035_ccfmc_lvds.gen/sources_1/bd/system/ip/system_system_ila_0_2/system_system_ila_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_system_ila_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/Projects/refSoM/refCC2/hw/vhfSystem.srcs/sources_1/bd/system/ip/system_system_ila_0_2/system_system_ila_0_2.xci
# IP: The module: 'system_system_ila_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/Projects/refSoM/refCC2/hw/adrv9361z7035_ccfmc_lvds.gen/sources_1/bd/system/ip/system_system_ila_0_2/bd_0/bd_1439.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1439 || ORIG_REF_NAME==bd_1439} -quiet] -quiet

# IP: e:/Projects/refSoM/refCC2/hw/adrv9361z7035_ccfmc_lvds.gen/sources_1/bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_0/bd_1439_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1439_ila_lib_0 || ORIG_REF_NAME==bd_1439_ila_lib_0} -quiet] -quiet

# XDC: e:/Projects/refSoM/refCC2/hw/adrv9361z7035_ccfmc_lvds.gen/sources_1/bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1439_ila_lib_0 || ORIG_REF_NAME==bd_1439_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/Projects/refSoM/refCC2/hw/adrv9361z7035_ccfmc_lvds.gen/sources_1/bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1439_ila_lib_0 || ORIG_REF_NAME==bd_1439_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/Projects/refSoM/refCC2/hw/adrv9361z7035_ccfmc_lvds.gen/sources_1/bd/system/ip/system_system_ila_0_2/bd_0/ip/ip_0/bd_1439_ila_lib_0_ooc.xdc

# XDC: e:/Projects/refSoM/refCC2/hw/adrv9361z7035_ccfmc_lvds.gen/sources_1/bd/system/ip/system_system_ila_0_2/bd_0/bd_1439_ooc.xdc

# XDC: e:/Projects/refSoM/refCC2/hw/adrv9361z7035_ccfmc_lvds.gen/sources_1/bd/system/ip/system_system_ila_0_2/system_system_ila_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_system_ila_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
