# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Projects/customDSPBringup/noGNUSystem/ccfmc_lvds/adrv9361z7035_ccfmc_lvds.srcs/sources_1/bd/system/ip/system_axi_gpreg_0/system_axi_gpreg_0.xci
# IP: The module: 'system_axi_gpreg_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Projects/customDSPBringup/noGNUSystem/ccfmc_lvds/adrv9361z7035_ccfmc_lvds.gen/sources_1/bd/system/ip/system_axi_gpreg_0/system_axi_gpreg_0_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpreg_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Projects/customDSPBringup/noGNUSystem/ccfmc_lvds/adrv9361z7035_ccfmc_lvds.gen/sources_1/bd/system/ip/xilinx/common/ad_rst_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpreg_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/Projects/customDSPBringup/noGNUSystem/ccfmc_lvds/adrv9361z7035_ccfmc_lvds.srcs/sources_1/bd/system/ip/system_axi_gpreg_0/system_axi_gpreg_0.xci
# IP: The module: 'system_axi_gpreg_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Projects/customDSPBringup/noGNUSystem/ccfmc_lvds/adrv9361z7035_ccfmc_lvds.gen/sources_1/bd/system/ip/system_axi_gpreg_0/system_axi_gpreg_0_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpreg_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Projects/customDSPBringup/noGNUSystem/ccfmc_lvds/adrv9361z7035_ccfmc_lvds.gen/sources_1/bd/system/ip/xilinx/common/ad_rst_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpreg_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
