webtalk_init -webtalk_dir D:/analog/hdl-hdl_2019_r2/projects/adrv9361z7035/ccfmc_lvds/adrv9361z7035_ccfmc_lvds.sim/sim_1/behav/xsim/xsim.dir/spiBusMonitor_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Oct 18 17:05:49 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212571552_0_0_763" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d7e425dd-8c22-4406-8302-9386e56d6f72" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e4b5916d595744c1991806779294c972" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6440HQ CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "179402850 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.58_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14624_KB" -context "xsim\\usage"
webtalk_transmit -clientid 737980218 -regid "212571552_0_0_763" -xml D:/analog/hdl-hdl_2019_r2/projects/adrv9361z7035/ccfmc_lvds/adrv9361z7035_ccfmc_lvds.sim/sim_1/behav/xsim/xsim.dir/spiBusMonitor_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/analog/hdl-hdl_2019_r2/projects/adrv9361z7035/ccfmc_lvds/adrv9361z7035_ccfmc_lvds.sim/sim_1/behav/xsim/xsim.dir/spiBusMonitor_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/analog/hdl-hdl_2019_r2/projects/adrv9361z7035/ccfmc_lvds/adrv9361z7035_ccfmc_lvds.sim/sim_1/behav/xsim/xsim.dir/spiBusMonitor_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
