# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/Projects/adrvSoM/vimanic/noGNUSystem/ccfmc_lvds/adrv9361z7035_ccfmc_lvds.srcs/sources_1/constraints/adrv9361z7035_constr.xdc

# XDC: E:/Projects/adrvSoM/vimanic/noGNUSystem/ccfmc_lvds/adrv9361z7035_ccfmc_lvds.srcs/sources_1/constraints/adrv9361z7035_constr_lvds.xdc

# XDC: E:/Projects/adrvSoM/vimanic/noGNUSystem/ccfmc_lvds/adrv9361z7035_ccfmc_lvds.srcs/sources_1/constraints/ccfmc_constr.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_angleLUT_0_0/system_angleLUT_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_angleLUT_0_0 || ORIG_REF_NAME==system_angleLUT_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_1 || ORIG_REF_NAME==system_axi_gpio_0_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_2/system_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_2 || ORIG_REF_NAME==system_axi_gpio_0_2} -quiet] -quiet

# IP: bd/system/ip/system_freqSynth_0_0/system_freqSynth_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_freqSynth_0_0 || ORIG_REF_NAME==system_freqSynth_0_0} -quiet] -quiet

# IP: bd/system/ip/system_amModulator_0_0/system_amModulator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_amModulator_0_0 || ORIG_REF_NAME==system_amModulator_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_ps7_0/system_sys_ps7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_ps7_0 || ORIG_REF_NAME==system_sys_ps7_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_ps7_axi_periph_0/system_sys_ps7_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_ps7_axi_periph_0 || ORIG_REF_NAME==system_sys_ps7_axi_periph_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_selectio_wiz_0_0/system_selectio_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_selectio_wiz_0_0 || ORIG_REF_NAME==system_selectio_wiz_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconcat_1_0/system_xlconcat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlconcat_1_0 || ORIG_REF_NAME==system_xlconcat_1_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0_0/system_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlconstant_0_0 || ORIG_REF_NAME==system_xlconstant_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_1_0/system_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlconstant_1_0 || ORIG_REF_NAME==system_xlconstant_1_0} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_1_0/system_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlslice_1_0 || ORIG_REF_NAME==system_xlslice_1_0} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_1_1/system_xlslice_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlslice_1_1 || ORIG_REF_NAME==system_xlslice_1_1} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_3_0/system_xlslice_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlslice_3_0 || ORIG_REF_NAME==system_xlslice_3_0} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_3_1/system_xlslice_3_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlslice_3_1 || ORIG_REF_NAME==system_xlslice_3_1} -quiet] -quiet

# IP: bd/system/ip/system_dataPackager_0_0/system_dataPackager_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_dataPackager_0_0 || ORIG_REF_NAME==system_dataPackager_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_iic_0_0/system_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_iic_0_0 || ORIG_REF_NAME==system_axi_iic_0_0} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/system/ip/system_i2sController_1_0/system_i2sController_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_i2sController_1_0 || ORIG_REF_NAME==system_i2sController_1_0} -quiet] -quiet

# IP: bd/system/ip/system_levelShift_0_0/system_levelShift_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_levelShift_0_0 || ORIG_REF_NAME==system_levelShift_0_0} -quiet] -quiet

# IP: bd/system/ip/system_envelopDetector_0_0/system_envelopDetector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_envelopDetector_0_0 || ORIG_REF_NAME==system_envelopDetector_0_0} -quiet] -quiet

# IP: bd/system/ip/system_subtractor_0_0/system_subtractor_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_subtractor_0_0 || ORIG_REF_NAME==system_subtractor_0_0} -quiet] -quiet

# IP: bd/system/ip/system_average_0_0/system_average_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_average_0_0 || ORIG_REF_NAME==system_average_0_0} -quiet] -quiet

# IP: bd/system/ip/system_average_0_1/system_average_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_average_0_1 || ORIG_REF_NAME==system_average_0_1} -quiet] -quiet

# IP: bd/system/ip/system_average_0_2/system_average_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_average_0_2 || ORIG_REF_NAME==system_average_0_2} -quiet] -quiet

# IP: bd/system/ip/system_clockCounter_0_0/system_clockCounter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_clockCounter_0_0 || ORIG_REF_NAME==system_clockCounter_0_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_1/system_system_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_system_ila_0_1 || ORIG_REF_NAME==system_system_ila_0_1} -quiet] -quiet

# IP: bd/system/ip/system_attenuatorController_0_0/system_attenuatorController_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_attenuatorController_0_0 || ORIG_REF_NAME==system_attenuatorController_0_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: e:/Projects/adrvSoM/vimanic/noGNUSystem/ccfmc_lvds/adrv9361z7035_ccfmc_lvds.gen/sources_1/bd/system/system_ooc.xdc
