webtalk_init -webtalk_dir E:/Projects/viv_2019/analogDriverTest/ccfmc_lvds/adrv9361z7035_ccfmc_lvds.sim/sim_1/behav/xsim/xsim.dir/decimation_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Nov 17 11:59:27 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212139570_0_0_700" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1f0fa751-cc9f-48fc-9733-e4f2c35244a0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e4b5916d595744c1991806779294c972" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2904 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "4 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6556_KB" -context "xsim\\usage"
webtalk_transmit -clientid 110575072 -regid "212139570_0_0_700" -xml E:/Projects/viv_2019/analogDriverTest/ccfmc_lvds/adrv9361z7035_ccfmc_lvds.sim/sim_1/behav/xsim/xsim.dir/decimation_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/Projects/viv_2019/analogDriverTest/ccfmc_lvds/adrv9361z7035_ccfmc_lvds.sim/sim_1/behav/xsim/xsim.dir/decimation_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/Projects/viv_2019/analogDriverTest/ccfmc_lvds/adrv9361z7035_ccfmc_lvds.sim/sim_1/behav/xsim/xsim.dir/decimation_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
