# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Projects/refSoM/refCC2/hw/vhfSystem.srcs/sources_1/bd/system/ip/system_sys_ps7_0/system_sys_ps7_0.xci
# IP: The module: 'system_sys_ps7_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Projects/refSoM/refCC2/hw/adrv9361z7035_ccfmc_lvds.gen/sources_1/bd/system/ip/system_sys_ps7_0/system_sys_ps7_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_sys_ps7_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/Projects/refSoM/refCC2/hw/vhfSystem.srcs/sources_1/bd/system/ip/system_sys_ps7_0/system_sys_ps7_0.xci
# IP: The module: 'system_sys_ps7_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Projects/refSoM/refCC2/hw/adrv9361z7035_ccfmc_lvds.gen/sources_1/bd/system/ip/system_sys_ps7_0/system_sys_ps7_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_sys_ps7_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
